<?php

declare(strict_types=1);

namespace CodeVault\Reports;

use CodeVault\Ai\AiProvider;
use CodeVault\Ai\AiSettings;
use CodeVault\Billing\CurrencyRepository;
use CodeVault\Billing\InvoiceRepository;
use CodeVault\Billing\OrderRepository;
use CodeVault\Billing\ServiceRepository;
use CodeVault\Cache\Cache;
use CodeVault\Clients\ClientRepository;
use CodeVault\Domains\DomainRepository;
use CodeVault\Modules\WidgetModule;
use CodeVault\Support\TicketRepository;

/**
 * AI Insights dashboard widget — a natural-language business summary of
 * the same headline numbers AdminDashboardController already aggregates
 * (income, new clients, pending orders, overdue, open tickets, renewals).
 *
 * The numbers are computed locally and only the *interpretation* is asked
 * of the AI, so the widget never depends on the LLM for its facts — if the
 * AI provider is unreachable, unconfigured, or errors out, the card still
 * renders the plain figures (the AI text is the garnish, not the dish).
 *
 * The summary is cached for an hour (same seam as the sitemap/catalog
 * listings) so an admin refreshing the dashboard doesn't burn a DeepSeek
 * call — and so the page stays fast.
 */
final class AiInsightsWidget implements WidgetModule
{
    private const CACHE_KEY = 'ai_insights_dashboard_v1';
    private const CACHE_TTL_SECONDS = 3600;
    private const RENEWAL_WINDOW_DAYS = 7;

    public function __construct(
        private readonly AiProvider $ai,
        private readonly AiSettings $settings,
        private readonly Cache $cache,
        private readonly ClientRepository $clients,
        private readonly OrderRepository $orders,
        private readonly InvoiceRepository $invoices,
        private readonly TicketRepository $tickets,
        private readonly ServiceRepository $services,
        private readonly DomainRepository $domains,
        private readonly CurrencyRepository $currencies
    ) {
    }

    public function metadata(): array
    {
        return [
            'name' => 'AI Insights',
            'description' => 'A natural-language summary of your business health from the shared AI provider.',
            'version' => '1.0.0',
            'author' => 'CodeVault',
        ];
    }

    public function configOptions(): array
    {
        return [];
    }

    public function placement(): string
    {
        return 'dashboard';
    }

    public function render(): string
    {
        $data = $this->snapshot();
        $summary = $this->cachedSummary($data);

        $card = '<div class="cv-card">'
            . '<h2 class="cv-card__title">✨ AI Insights</h2>';

        if ($summary !== null) {
            $card .= '<div style="line-height:1.7;color:var(--cv-text-primary);white-space:pre-line;font-size:.95rem;">'
                . e($summary)
                . '</div>'
                . '<div style="margin-top:var(--cv-space-3);font-size:var(--cv-text-xs);color:var(--cv-text-tertiary);">'
                . 'Generated by ' . e($this->settings->model()) . ' · refreshed hourly · '
                . '<a href="/admin/settings/ai" style="color:var(--cv-color-brand-500);">Manage AI</a>'
                . '</div>';
        } else {
            $card .= '<div style="line-height:1.7;color:var(--cv-text-secondary);font-size:.9rem;">'
                . $this->plainFacts($data)
                . '</div>';

            if (!$this->settings->hasKey()) {
                $card .= '<p style="margin-top:var(--cv-space-3);font-size:var(--cv-text-xs);color:var(--cv-text-tertiary);">'
                    . 'AI summary unavailable — configure an AI provider key under '
                    . '<a href="/admin/settings/ai" style="color:var(--cv-color-brand-500);">AI Settings</a> to unlock natural-language insights.'
                    . '</p>';
            } else {
                $card .= '<p style="margin-top:var(--cv-space-3);font-size:var(--cv-text-xs);color:var(--cv-text-tertiary);">'
                    . 'AI summary unavailable right now — showing live figures instead. It will retry on the next refresh.'
                    . '</p>';
            }
        }

        return $card . '</div>';
    }

    /**
     * The live numbers, always computed locally.
     *
     * @return array<string, mixed>
     */
    private function snapshot(): array
    {
        $default = $this->currencies->default();

        return [
            'income_this_month' => $this->invoices->totalPaidThisMonth(),
            'new_clients_this_month' => $this->clients->countNewThisMonth(),
            'total_clients' => $this->clients->countAll(),
            'pending_orders' => $this->orders->countPending(),
            'overdue_invoice_count' => $this->invoices->countOverdue(),
            'overdue_invoice_total' => $this->invoices->sumOverdue(),
            'open_tickets' => $this->tickets->countOpen(),
            'renewing_services' => $this->services->countDueForBilling(self::RENEWAL_WINDOW_DAYS),
            'renewing_domains' => $this->domains->countDueForRenewal(self::RENEWAL_WINDOW_DAYS),
            'currency_symbol' => (string) ($default['symbol'] ?? '$'),
            'currency_code' => (string) ($default['code'] ?? 'USD'),
        ];
    }

    /**
     * The AI-written interpretation, cached. Returns null when the AI
     * can't be reached (or is unconfigured) so the caller falls back to
     * the plain figures.
     */
    private function cachedSummary(array $data): ?string
    {
        return $this->cache->remember(self::CACHE_KEY, self::CACHE_TTL_SECONDS, function () use ($data): ?string {
            if (!$this->settings->hasKey()) {
                return null;
            }

            $systemPrompt = 'You are the business-insights assistant for a web hosting company\'s billing '
                . 'platform. Given a set of dashboard numbers, write a concise 3-6 sentence plain-text summary '
                . 'of the business\'s current health. Be specific and reference the actual figures. Flag anything '
                . 'that deserves attention (e.g. high overdue totals, a surge of pending orders). Do NOT use '
                . 'markdown, headings, or bullet lists — just a short paragraph of plain sentences.';

            $result = $this->ai->complete($systemPrompt, $this->describe($data));

            return $result['success'] ? trim((string) $result['text']) : null;
        });
    }

    /** @param array<string, mixed> $data */
    private function describe(array $data): string
    {
        $sym = $data['currency_symbol'];

        return implode("\n", [
            'Income this month: ' . $sym . number_format((float) $data['income_this_month'], 2) . ' (' . $data['currency_code'] . ')',
            'New clients this month: ' . (int) $data['new_clients_this_month'] . ' (total clients: ' . (int) $data['total_clients'] . ')',
            'Pending orders: ' . (int) $data['pending_orders'],
            'Overdue invoices: ' . (int) $data['overdue_invoice_count'] . ' totalling ' . $sym . number_format((float) $data['overdue_invoice_total'], 2),
            'Open support tickets: ' . (int) $data['open_tickets'],
            'Services renewing within 7 days: ' . (int) $data['renewing_services'],
            'Domains renewing within 7 days: ' . (int) $data['renewing_domains'],
        ]);
    }

    /** @param array<string, mixed> $data */
    private function plainFacts(array $data): string
    {
        $sym = $data['currency_symbol'];

        return '<strong>' . $sym . number_format((float) $data['income_this_month'], 2) . '</strong> income this month · '
            . '<strong>' . (int) $data['new_clients_this_month'] . '</strong> new clients · '
            . '<strong>' . (int) $data['pending_orders'] . '</strong> pending orders · '
            . '<strong>' . (int) $data['overdue_invoice_count'] . '</strong> overdue invoices · '
            . '<strong>' . (int) $data['open_tickets'] . '</strong> open tickets · '
            . '<strong>' . (int) $data['renewing_services'] . '</strong> services renewing soon';
    }
}
