<?php

declare(strict_types=1);

namespace CodeVault\Billing;

use CodeVault\Clients\ClientRepository;
use CodeVault\Cron\CronJob;
use CodeVault\Mail\EmailDispatcher;

/**
 * Lifecycle email (blueprint §4.4/§5 marketing automation) — reminds a
 * client their service is renewing soon, ahead of (and independent from)
 * the actual renewal invoice generated by RecurringBillingService. Each
 * service is reminded at most once per cycle (ServiceRepository::
 * dueForReminder() only returns rows with renewal_reminded_at IS NULL;
 * advanceNextDueDate() clears it again once the cycle rolls over).
 */
final class RenewalReminderJob implements CronJob
{
    public const DEFAULT_DAYS_AHEAD = 7;

    public function __construct(
        private readonly ServiceRepository $services,
        private readonly ClientRepository $clients,
        private readonly EmailDispatcher $mail
    ) {
    }

    public function name(): string
    {
        return 'service-renewal-reminder';
    }

    public function frequencyMinutes(): int
    {
        return 1440;
    }

    public function handle(): void
    {
        foreach ($this->services->dueForReminder(self::DEFAULT_DAYS_AHEAD) as $service) {
            $client = $this->clients->find((int) $service['client_id']);

            if ($client === null) {
                continue;
            }

            $this->mail->sendTemplate('service_renewal_reminder', $client['email'], [
                'first_name' => $client['first_name'],
                'product_name' => $service['product_name'],
                'due_date' => $service['next_due_date'],
                'amount' => number_format((float) $service['amount'], 2),
                'company_name' => 'CodeVault',
            ], (int) $client['id']);

            $this->services->stampReminded((int) $service['id']);
        }
    }
}
